name: Deploy Workflow new

on:
  pull_request:
    types:
      - closed

jobs:
  manual_approval:
      runs-on: ubuntu-latest
      steps:

        - name: Install Dependencies
          run: |
            python -m pip install --upgrade pip
            pip install pytest pytest-cov pylint flake8 mypy bandit
    
        - name: Run Final Steps
          run: |
            pytest --cov=python--cov-fail-under=60

