name: Deploy Workflow new

on:
  pull_request:
    types:
      - closed

jobs:
  manual_approval:
    runs-on: ubuntu-latest
    needs: pytest_coverage.initial_steps
    steps:

      - name: Run Final Steps
        run: |
          pytest --cov=calculator --cov-fail-under=60
