name: Deploy Workflow new

on:
  pull_request:
    types:
      - closed

jobs:
  initial_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Initial Deployment Steps
        run: |
          echo "Initial deployment steps go here"

  manual_approval:
    runs-on: ubuntu-latest
    needs: initial_steps
    steps:
      - name: Run Final Steps
        run: |
          pytest --cov=calculator --cov-fail-under=60

