name: Manual Approval Workflow

on:
  pull_request_review:
    types:
      - submitted

jobs:
  manual_approval:
    runs-on: ubuntu-latest

    steps:
      - name: Check if PR is approved
        id: pr_approved
        run: echo "::set-output name=approved::$(if [ -n \"${{ github.event.review.state }}\" ] && [ \"${{ github.event.review.state }}\" == \"approved\" ]; then echo \"true\"; else echo \"false\"; fi)"

      - name: Wait for PR approval
        run: sleep 10

      - name: Run Final Steps
        if: steps.pr_approved.outputs.approved == 'true' && github.event_name == 'pull_request_review'
        run: |
          pytest --cov=calculator --cov-fail-under=60
          # Additional steps for final stages
