name: Main CI Build Workflow

on:
  pull_request:
    types:
      - opened

jobs:
  initial_steps:
    runs-on: ubuntu-latest

    steps:
    
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      - name: DemoSonarCloudSCan
        uses: actions/checkout@v3
        with:
            fetch-depth: 0

      - name: SonarScanner SCAN
        run: sonar-scanner -Dsonar.login=${{ secrets.SONAR_TOKEN }} -Dsonar.projectKey=Densingmoses123_ghactions

       
