name: Main CI Build Workflow

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - labeled
      - review_requested
      - review_request_removed

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    
    steps:
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov
