name: Main CI Build Workflow

on:
  pull_request:
    types:
      - opened

jobs:
  initial_steps:
    runs-on: ubuntu-latest

    steps:
    
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      - name: DemoSonarCloudSCan
        uses: actions/checkout@v3
        with:
            fetch-depth: 0
            
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
            GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
              -Dsonar.organization=densingmoses123
              -Dsonar.projectKey=ghactions
              -Dsonar.python.coverage.reportPaths=coverage.xml
